spring:
#  # 配置数据库连接池,目前 不采用 mysql,暂时先保留,后续再说
#  datasource:
#    url: jdbc:mysql://localhost:3306/daoki?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
#    username: root
#    password: 123456

  data:
    mongodb:
      database: daoki
      uri: mongodb://127.0.0.1:27017